### ISSUE TITLE
Halting on Converting Boundary Conditions for Large Meshes

### ISSUE THREAD

**Issue by 7mTo** [yhaomin2007/Nek5000#3]
I created a large mesh with the following stats:
- total node number is     22125859
- total quad element number is       674730
- total hex element number is      2601000
As read by gmsh2nek. Of course prior to that, I had to increase MAXNEL to 30000000 and recompile. However, after the tools is done reading the mesh, it starts converting boundary conditions, where I don't specify any, and halts. I allowed it 24 hours before writing this issue and it is still halting. The size of my mesh is 6GB. I can share it with you through Mega or Google Drive.

Is there an easy fix to skip boundary condition conversion altogether?

**Comment by 7mTo** [comment]
Upon further inspection, it seems that the mesh is just too large to handle on one core. Is your code parallelizable?

**Comment by yhaomin2007** [comment]
hI, i believe you are using an old version code.
Please update to current version and recompile.

the problem you see is due to old scheme of boundary search.
I update this scheme, and it is much faster now. 
For 1million element mesh, it could be converted in 5 mins.

**Comment by 7mTo** [comment]
You are correct. I was using an old version.

I updated the tool and recompiled and it works much faster now.
